---
title: "Binär logistische Regression "
engine: knitr
execute:
  eval: true
  echo: true
---


## Idee und Einführung

-   **Idee:**
    -   Abhängigkeit einer dichotomen Variablen von
        **_unabhängigen Variablen / Regressoren_**
    -   **_binär/dichotom:_** *ja/nein*, *trifft zu/ trifft nicht zu*,
        *männlich/weiblich*, *Raucher/nicht Raucher*

-   **Dummy-Variable:**
    -   Ebenfalls 0/1 codiert mit Bedeutung z.B. *ja/nein*
    -   wird allgemein verwendet für unabhängige **und** abhängige Variablen

-   **Beispiel: Studie zur Verkehrsmittelwahl**
    -   Pendlerfahrten: Arbeitsplatz $\ra$ zu Hause
    -   $\ra$ Privatauto vs. öffentlicher Nahverkehr (ÖV)
    -   Datensatz `verkersmittel.csv` mit den Variablen
    -   **mode:** Verkehrsmittel ($0 = $ Privatauto  vs. $ 1 = $ ÖV)
    -   **zeit:** Fahrzeitdifferenz zwischen ÖV und Auto
    -   **kosten:** Kostendifferenz zwischen ÖV und Auto
    -   **geschlecht:** 1 = weiblich $\ra$ 2 = männlich
    -   **umsteigen:** Zahl notwendiger Umstiege bei Nutzung der ÖV

-   **Fragestellung:** Von welchen Faktoren hängt die Wahl des
    Verkehrsmittels ab?
