name: Quarto Publish

on:
  push:
    branches: [main]
    paths:
      - "**/*.qmd"
      - "**/*.md"
      - "_quarto.yml"
      - "_metadata.yml"
      - "styles/**"
      - "figs/**"
      - "assets/**"
      - "include/**"
      - "requirements.txt"
      - ".github/workflows/publish.yml"
  workflow_dispatch:

concurrency:
  group: quarto-publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1) Repo
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 2) Python with pip cache
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      # 3) Install deps (will be fast on cache hits)
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Cache jupyter-cache and freeze cache (optional but useful)
      - name: Cache jupyter-cache
        uses: actions/cache@v4
        with:
          path: .jupyter_cache
          key: jcache-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('_quarto.yml', 'include/**/*.ipynb', 'include/**/*.qmd', '*.qmd') }}
          restore-keys: |
            jcache-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}-

      - name: Cache _freeze
        uses: actions/cache@v4
        with:
          path: _freeze
          key: freeze-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('_quarto.yml', 'include/**/*.ipynb', 'include/**/*.qmd', '*.qmd') }}
          restore-keys: |
            freeze-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}-

      # 5) Quarto CLI
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.7.31"   # match local version for reproducibility

      # 6) Render site (force default kernel so CI doesn't need 'gki-venv')
      - name: Render site
        env:
          QUARTO_PYTHON: ${{ env.pythonLocation }}/bin/python
        run: |
          quarto render --execute-kernel=python3

      # 7) Publish already-rendered site (no re-render)
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
