on:
  push:
    branches: [main]
    paths:
      - "**/*.qmd"
      - "**/*.md"
      - "_quarto.yml"
      - "_metadata.yml"
      - "styles/**"
      - "figs/**"
      - "assets/**"
      - "include/**"
      - "requirements.txt"
      - ".github/workflows/publish.yml"
  workflow_dispatch:

name: Quarto Publish

concurrency:
  group: quarto-publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1) Repo
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 2) Python (enable pip cache)
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: requirements.txt

      # 3) Install deps
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Minimal Quarto caches (speed up notebook builds)
      - name: Cache jupyter-cache
        uses: actions/cache@v4
        with:
          path: .jupyter_cache
          key: jcache-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            jcache-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-

      - name: Cache _freeze
        uses: actions/cache@v4
        with:
          path: _freeze
          key: freeze-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            freeze-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-

      # 5) Keep your kernel approach
      - name: Register gki-venv kernelspec on runner
        run: |
          python -m ipykernel install --user --name gki-venv --display-name "gki-venv"
          jupyter kernelspec list

      # 6) Quarto CLI
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.7.31"

      # 7) Render & publish
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          QUARTO_PYTHON: ${{ env.pythonLocation }}/bin/python
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
